User's Guide
------------

Entire documentation of Distill lives here. Provides
step by step instructions to install Distill and a
full fleshed out API documentation.

.. toctree::
   :maxdepth: 2

   installation
   quickstart

API Reference
-------------

.. toctree::
   :maxdepth: 2


   api

Additional Notes
----------------

Design notes, legal information and changelong are here.

.. toctree::
   :maxdepth: 2

   changelog
   license
