User's Guide
------------

Entire documentation of Distill lives here. Provides
step by step instructions to install and deploy Distill in a 
development and production environment. Including is a API reference
portal and quickstart quide.

.. toctree::
   :maxdepth: 2

   installation
   quickstart

API Reference
-------------

.. toctree::
   :maxdepth: 2

   api

Additional Notes
----------------

Design notes, legal information and changelong are here.

.. toctree::
   :maxdepth: 2

   changelog
   license
